/*
 *   Copyright (c) Gejian Semiconductors 2023
 *   All rights reserved.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef CAN_TEST_H_
#define CAN_TEST_H_

#include "device.h"
#include "mcan.h"
#include "bsp_can.h"

#define CAN_TX_GPIO             32
#define CAN_RX_GPIO             11
#define CAN_TX_GPIO_MUX         GPIO_32_CANA_TX
#define CAN_RX_GPIO_MUX         GPIO_11_CANA_RX
#define CAN_BASE                CANA_BASE
#define CAN_BAUD                500000
#define CAN_IRQ_NUMBER          INT_CANA0

extern MCAN_RxMessage_t can_rx_msg;
extern uint8_t can_tx_msg[8];

void can_test_init(void);
void can_test_run(void);

#endif /* CAN_TEST_H_ */
