/*
 *   Copyright (c) Gejian Semiconductors 2023
 *   All rights reserved.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef CMPSS_TEST_H_
#define CMPSS_TEST_H_

#include "device.h"
#include "bsp_cmpss.h"

/* ---- CMPSS1: 参照 cmpss_board.h ---- */
#define CMPSS_GPIO_PIN              242U
#define CMPSS_BASE                  CMPSS3_BASE
#define CMPSS_HP_MUX_SELECT         ASYSCTL_CMPHPMUX_SELECT_3
#define CMPSS_LP_MUX_SELECT         ASYSCTL_CMPLPMUX_SELECT_3
#define CMPSS_HP_CHANNEL            CMP_HP_LP_3
#define CMPSS_LP_CHANNEL            CMP_HP_LP_3

/* ---- DAC 阈值（12bit, VDDA=3.3V, 1LSB≈0.806mV）---- */
#define CMPSS_DAC_HIGH              2048U    /* 1.65V */
#define CMPSS_DAC_LOW               2000U    /* 1.61V */

/* ---- 获取比较器状态宏 ---- */
#define CMPSS_GET_HIGH_OUT()    (CMPSS_getStatus(CMPSS_BASE) & CMPSS_STS_HI_FILTOUT)
#define CMPSS_GET_LOW_OUT()     (CMPSS_getStatus(CMPSS_BASE) & CMPSS_STS_LO_FILTOUT)

void cmpss_test_init(void);
void cmpss_test_run(void);
void CMPSS_ReadResults(void);

#endif /* CMPSS_TEST_H_ */
