/*
 *   Copyright (c) Gejian Semiconductors 2023
 *   All rights reserved.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#include "hrpwm_test.h"

volatile float hrpwma_duty = HRPWMA_DUTY;
volatile float hrpwmb_duty = HRPWMB_DUTY;

/* ---- HRPWM test init ---- */
void hrpwm_test_init(void)
{
    /* ---- 时钟同步暂停 ---- */
    SysCtl_disablePeripheral(SYSCTL_PERIPH_CLK_TBCLKSYNC);

    /* ---- HRPWMA: 互补 (GPIO0/1, EPWM1) ---- */
    HRPWM_GPIO_Init(HRPWMA_GPIO_A_MUX, HRPWMA_GPIO_A, HRPWMA_GPIO_B_MUX, HRPWMA_GPIO_B);
    HRPWM_Module_Init(HRPWMA_BASE, HRPWMA_PERIOD, true, HRPWMA_DEADTIME_US);
    HRPWM_SetDuty(HRPWMA_BASE, HRPWMA_PERIOD, HRPWMA_DUTY, HRPWM_COUNTER_COMPARE_A, HRPWM_COUNTER_COMPARE_B);

    /* ---- HRPWMB: 独立 (GPIO7, EPWM2) ---- */
    HRPWM_GPIO_Init(HRPWMB_GPIO_A_MUX, HRPWMB_GPIO_A, 0, 0);
    HRPWM_Module_Init(HRPWMB_BASE, HRPWMB_PERIOD, false, 0.0f);
    HRPWM_SetDuty(HRPWMB_BASE, HRPWMB_PERIOD, HRPWMB_DUTY, HRPWM_COUNTER_COMPARE_A, 0);

    /* ---- 时钟同步恢复 ---- */
    SysCtl_enablePeripheral(SYSCTL_PERIPH_CLK_TBCLKSYNC);
}

/* ---- HRPWM test run ---- */
void hrpwm_test_run(void)
{
	 /* 示波器查看 GPIO0 GPIO1 GPIO7, GDB 修改 hrpwma_duty 和 hrpwmb_duty*/

	while(1)
	{
		HRPWM_SetDuty(HRPWMA_BASE, HRPWMA_PERIOD, hrpwma_duty, HRPWM_COUNTER_COMPARE_A, HRPWM_COUNTER_COMPARE_B);
		HRPWM_SetDuty(HRPWMB_BASE, HRPWMB_PERIOD, hrpwmb_duty, HRPWM_COUNTER_COMPARE_A, 0);
		DELAY_US(1000 * 200);
	}
}
