/*
 *   Copyright (c) Gejian Semiconductors 2023
 *   All rights reserved.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef I2C_TEST_H_
#define I2C_TEST_H_

#include "device.h"
#include "bsp_i2c.h"

#define AT24C64_SDA_GPIO        35
#define AT24C64_SCL_GPIO        37
#define AT24C64_SDA_GPIO_MUX    GPIO_35_I2CA_SDA
#define AT24C64_SCL_GPIO_MUX    GPIO_37_I2CA_SCL
#define AT24C64_I2C_BASE        I2CA_BASE
#define AT24C64_I2C_ADDR        0x50
#define AT24C64_I2C_BITRATE     400

extern volatile uint8_t eeprom_read_data[5];
extern volatile uint8_t eeprom_write_data[5];
extern volatile bool eeprom_write_flag;

void i2c_test_init(void);
void i2c_test_run(void);

#endif /* I2C_TEST_H_ */
