/*
 *   Copyright (c) Gejian Semiconductors 2023
 *   All rights reserved.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef SCI_TEST_H_
#define SCI_TEST_H_

#include "device.h"
#include "bsp_sci.h"

extern uint16_t rx_data;

#define SCI_TX_GPIO_MUX         GPIO_29_SCIA_TX
#define SCI_RX_GPIO_MUX         GPIO_28_SCIA_RX
#define SCI_TX_GPIO             29
#define SCI_RX_GPIO             28
#define SCI_BASE                SCIA_BASE
#define SCI_BAUD                256000
#define SCI_IRQ_NUMBER          INT_SCIA_RX

#define RS485_TX_GPIO_MUX       GPIO_224_SCIC_TX
#define RS485_RX_GPIO_MUX       GPIO_226_SCIC_RX
#define RS485_TX_GPIO           224
#define RS485_RX_GPIO           226
#define RS485_BASE              SCIC_BASE
#define RS485_BAUD              256000
#define RS485_IRQ_NUMBER        INT_SCIC_RX

void sci_test_init(void);
void sci_test_run(void);

#endif /* SCI_TEST_H_ */
