/*
 *   Copyright (c) Gejian Semiconductors 2023
 *   All rights reserved.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef BSP_CPUTIMER_H_
#define BSP_CPUTIMER_H_

#include "inc/hw_types.h"
#include "inc/hw_memmap.h"

/* ---- Base ---- */
#define BSP_CPUTIMER_BASE       CPUTIMER0_BASE

/* ---- 默认定时周期（APBCLK 周期数，100Hz = 10ms） ---- */
#define BSP_CPUTIMER_PERIOD     (DEVICE_APBCLK_FREQ / 100U)

/* ---- 中断号 ---- */
#define BSP_CPUTIMER_IRQ        INT_TIMER0

void CPUTimer_Clock_Init(void);
void CPUTimer_Module_Init(uint32_t base, uint32_t period, IRQn_Type IRQn, IrqHandlerType handler);
void CPUTimer_Init(uint32_t base, uint32_t period, IRQn_Type IRQn, IrqHandlerType handler);

#endif /* BSP_CPUTIMER_H_ */
