/*
 *   Copyright (c) Gejian Semiconductors 2023
 *   All rights reserved.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef BSP_GPIO_BSP_GPIO_H_
#define BSP_GPIO_BSP_GPIO_H_

#include "inc/hw_types.h"
#include "inc/hw_memmap.h"

#define BSP_INT1_GPIO_MUX           GPIO_233_GPIO233
#define BSP_INT1_GPIO               233
#define BSP_INT2_GPIO_MUX           GPIO_237_GPIO237
#define BSP_INT2_GPIO               237
#define BSP_INT3_GPIO_MUX           GPIO_231_GPIO231
#define BSP_INT3_GPIO               231
#define BSP_INT4_GPIO_MUX           GPIO_238_GPIO238
#define BSP_INT4_GPIO               238
#define BSP_INT5_GPIO_MUX           GPIO_241_GPIO241
#define BSP_INT5_GPIO               241
#define BSP_INT6_GPIO_MUX           GPIO_225_GPIO225
#define BSP_INT6_GPIO               225

void EXTI_AIO_Init(uint32_t pinCfg, uint32_t pin, GPIO_ExternalIntNum extIntNum, IRQn_Type irq, IrqHandlerType handler);

#endif /* BSP_GPIO_BSP_GPIO_H_ */
