/*
 *   Copyright (c) Gejian Semiconductors 2023
 *   All rights reserved.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#ifndef BSP_ADC_H_
#define BSP_ADC_H_

#include "inc/hw_types.h"
#include "inc/hw_memmap.h"

/* ---- Base ---- */
#define BSP_ADC_BASE            ADCA_BASE

/* ---- ADC 参考电压: 外部 3.3V ---- */
#define BSP_ADC_REF_MODE        ADC_REFERENCE_EXTERNAL
#define BSP_ADC_REF_VOLT        ADC_REFERENCE_3_3V

/* ---- ADC 时钟分频 ---- */
#define BSP_ADC_CLK_DIV         ADC_CLK_DIV_4_0

void ADC_Clock_Init(void);
void ADC_Module_Init(uint32_t base);
void ADC_Init(uint32_t base);
void ADC_DMA_Init(uint16_t *dstBuf, uint16_t count);

#endif /* BSP_ADC_H_ */
